# Generated by Django 4.2.18 on 2025-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streakly', '0002_habit_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcompletion',
            name='date',
            field=models.DateField(),
        ),
    ]
